### ISSUE TITLE
Moderation data types specification

### ISSUE THREAD

**Issue by micahscopes** [hyperhyperspace/wiki-collab#5]
Access groups:
- immutable root level individual or group who have **root permission**
- mutable editing membership group with **membership permission**
- stretch goal: mutable administrator group, modifiable by root permission, sitting between root and member permission

Permission modes:
- open vs. closed editing at the wiki level
  - a flag for open vs. closed
  - closed: closed to editing members
  - open: disregard authorized editor set, open to people with an identity
- stretch goal: per-page permissions

Other features:
- invite codes to add members

**Comment by micahscopes** [comment]
From the last conversation with @sbazerque:
> so the settings config would be down to two screens?: who the members are, and the setting for each capability (adding pages / writing content / reading the wiki, say? with each option being: anyone, members, owners only)

**Comment by sbazerque** [comment]
I propose conflating "adding pages" to "writing content", and with the beast working we try to evaluate if it makes sense making adding pages a different setting! then we're left with the two basic permissions "read" and "write".

**Comment by micahscopes** [comment]
The permissions model has been simplified even more:

#### Access groups
- **members**: includes owners and a set of members modifiable by those owners
- **anyone**

#### Permissions (members / anyone)
- **write**: allowed can modify pages, blocks and block contents
- **read**: trusted to receive and distribute updates

**Comment by micahscopes** [comment]
I think this is done
